package it.bit.gestionalecorsi.entities;

public enum Region {
    ABRUZZO, BASILICATA, CALABRIA, CAMPANIA,
    EMILIA_ROMAGNA, FRIULI_VENEZIA_GIULIA, LAZIO,
    LIGURIA, LOMBARDIA, MARCHE, MOLISE, PIEMONTE,
    PUGLIA, SARDEGNA, SICILIA, TOSCANA, TRENTINO_ALTO_ADIGE,
    UMBRIA, VALLE_DAOSTA, VENETO
}
